### ISSUE TITLE
Migrate to slotted dev-lang/lua and update to sys-cluster/lmod from science overlay

### ISSUE THREAD

**Issue by olifre** [EESSI/gentoo-overlay#36]
Gentoo is currently migrating to a slotted `dev-lang/lua`, i.e. slots `5.1`, `5.2` and `5.3` will be established:
https://packages.gentoo.org/packages/dev-lang/lua
and `app-eselect/eselect-lua` will be used to select the preferred implementation. 

A new `sys-cluster/lmod` ebuild available in the science overlay:
https://github.com/gentoo/sci/tree/master/sys-cluster/lmod
already makes use of these. 

Currently, the Lua slots are still `~` keyworded, though.

**Comment by bedroge** [comment]
I just did a quick test with this in a Prefix environment, but unfortunately the Lua libraries (`luaposix`, `luafilesystem`, `bit32`) in the Gentoo repos are still not working inside Prefix: they fail to install due to double prefixes. So I guess we should try to get those fixed first (by making a PR with our versions?).

**Comment by olifre** [comment]
> So I guess we should try to get those fixed first (by making a PR with our versions?).

That sounds like a good plan :+1: . While the queue of PRs is currently quite lengthy in `gentoo/gentoo` (I have several version bumps of my proxy-maintained packages pending since weeks), persisting the fix upstream is for sure for the best.

**Comment by bedroge** [comment]
I've done a bit of work on this, and have some working versions, but I just found that Gentoo is trying to patch the lua-utils.eclass (since it seems to affect all lua libraries):
https://bugs.gentoo.org/762769#c4

Maybe we should wait for that, and perhaps we can use patched versions in the meantime until their fix has been merged.

**Comment by bedroge** [comment]
I've tested the patch from the comment in that bug, and it works partially; I gave some feedback in that bug.

If we want to make a new release before this gets patched upstream: I've made a PR (#43) with the required patches that allowed me to install the lmod from the science overlay.

**Comment by bedroge** [comment]
Solved in #43 and #45. When the Lua patch gets merged upstream, we can remove it from our repo again.
